#! /usr/bin/perl

use DoQuery;

use DbCredentials;

sub make_query {
    my $id = shift;
    return <<EOF
select
	i.id as id,
	i.title as title,
	i.description as description,
 	doc.abbr as region,
  	group_concat(distinct ds.type order by ds.type separator ', ') data_type,
	i.attributes as var_type,
 	doc.name as assoc_report,
	who.name as image_source,	
	group_concat(distinct ds.name order by ds.name separator ', ') data_source_title,
 	group_concat(distinct ds.url order by ds.name separator ', ') data_source_url,
	group_concat(distinct image_files.file order by image_files.file separator ', ') image_files,
 	group_concat(distinct data_files.file order by data_files.file separator ', ') data_files,
	group_concat(distinct metadata_files.file order by metadata_files.file separator ', ') metadata_files,
	group_concat(distinct doc_files.file order by doc_files.file separator ', ') doc_files
from image i
left outer join document doc on i.document_id = doc.id
left outer join image_dataset on i.id = image_dataset.image_id
left outer join dataset ds on image_dataset.dataset_id = ds.id
left outer join image_creator im_who on im_who.image_id = i.id
left outer join who on who.id = im_who.who_id
left outer join (
	select
		image_id,
		file_type,
		concat(dir, file) file
	from file 
	where file.image_id = $id
		and file_type = 'IMAGE'
) image_files on image_files.image_id = i.id

left outer join (
	select
		image_id,
		file_type,
		concat(dir, file) file
	from file 
	where file.image_id = $id
		and file_type = 'DATA'
) data_files on data_files.image_id = i.id
left outer join (
	select
		image_id,
		file_type,
		concat(dir, file) file
	from file 
	where file.image_id = $id
		and file_type = 'METADATA'
) metadata_files on metadata_files.image_id = i.id
left outer join (
	select
		image_id,
		file_type,
		concat(dir, file) file
	from file 
	where file.image_id = $id
		and file_type = 'DOC'
) doc_files on doc_files.image_id = i.id
where i.id = $id
EOF
;
}

$dbh = DoQuery::Connect($DbCredentials::database, $DbCredentials::username, $DbCredentials::password);

$sth0 = DoQuery::DoQuery("select id from image");
while ($hr0 = $sth0->fetchrow_hashref()) {
    $sth = DoQuery::DoQuery(make_query($hr0->{id}));
    if ($hr = $sth->fetchrow_hashref()) {
        @fields = (
            $hr->{id},
            $dbh->quote(  $hr->{title}              ),
            $dbh->quote(  $hr->{description}        ),
            $dbh->quote(  $hr->{region}             ),
            $dbh->quote(  $hr->{data_type}          ),
            $dbh->quote(  $hr->{var_type}           ),
            $dbh->quote(  $hr->{assoc_report}       ),
            $dbh->quote(  $hr->{image_source	}   ),
            $dbh->quote(  $hr->{data_source_title}  ),
            $dbh->quote(  $hr->{data_source_url}    ),
            $dbh->quote(  $hr->{image_files}        ),
            $dbh->quote(  $hr->{data_files}         ),
            $dbh->quote(  $hr->{metadata_files}     ),
            $dbh->quote(  $hr->{doc_files}          )
            );        
        printf("%s\n", join(",", @fields));
    } else {
        printf(";;; ERROR for id=%s\n", $hr0->{id});
    }
}
