#! /usr/bin/perl

@newterms = (
'CO2 Concentrations',
'Cost of Damage',
'Drought Trends',
'Freezing Level',
'Greenhouse Gas Emissions',
'Hurricane Strikes',
'Ice Area',
'Lake Ice Cover',
'Lake Water Level',
'Lake Water Surface Temperature',
'PDO Index',
'Sea Ice Area',
'Sea Level',
'Sea Surface Temperature',
'Snow Depth',
'Storm Surge Height',
'Stream Flow',
'TC Occurrence',
'Tornado Count',
'Wind'
    );

sub sql {
    my $cmd = shift;
    print "$cmd\n";
}

#sql("update taxonomy_term_data set name='Sea' where tid=23;");

foreach $term (@newterms) {
    sql("insert into taxonomy_term_data (vid,name,description,format,weight) values (6,'$term','','filtered_html',0);");
}

#insert into taxonomy_term_hierarchy (tid,parent) (select tid,0 from taxonomy_term_data where vid = (select vid from taxonomy_vocabulary where name='Variable Type') and tid > 23 and tid not in (select tid from taxonomy_term_hierarchy))
