#! /usr/bin/perl

@newterms = (
'Greenhouse Gases',
'Snow',
'Rivers',
'Water Level',
'Tornadoes',
'Models',
'Lakes',
'Tropical Cyclones',
'Ice',
'Wind',
'Disasters',
'Weather',
'Drought',
    );

sub sql {
    my $cmd = shift;
    print "$cmd\n";
}

sql("update taxonomy_term_data set name='Sea' where tid=23;");

foreach $term (@newterms) {
    sql("insert into taxonomy_term_data (vid,name,description,format,weight) values (6,'$term','','filtered_html',0);");
}
